/**
 * this file is auto generated by TTO-CodeGenerator v{{.version}} !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/ixre/tto
 *
 */

package {{pkg "go" .global.Pkg}};

/** {{.table.Comment}} */
class {{.table.Title}}{
    {{range $i,$c:=.columns}}
    /** {{$c.Comment}} */
    var {{lowerTitle $c.Title}}:{{type "kotlin" $c.TypeId}} = {{end}}
}