/**
 * this file is auto generated by TTO-CodeGenerator v{{.global.version}} !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/ixre/tto
 *
 */
#!target:kotlin/{{.global.pkg}}/repo/{{.table.Title}}Repository.kt
package {{pkg "java" .global.pkg}}.repo;

import {{pkg "java" .global.pkg}}.pojo.{{.table.Title}}Entity
import org.springframework.data.jpa.repository.JpaRepository
{{$pkType := type "kotlin" .table.PkType}}
/** {{.table.Comment}}仓储接口  */
interface {{.table.Title}}Repository : JpaRepository<{{.table.Title}}Entity, {{$pkType}}> {

}