/**
 * this file is auto generated by TTO-CodeGenerator v{{.global.Version}} !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/ixre/tto
 *
 */
!target:kotlin/{{.global.Pkg}}/service/{{.table.Title}}Service.kt
package {{pkg "java" .global.Pkg}}.service

import {{pkg "java" .global.Pkg}}.pojo.{{.table.Title}}Entity
import {{pkg "java" .global.Pkg}}.repo.{{.table.Title}}Repository
import org.springframework.stereotype.Service
import java.util.*
import javax.annotation.Resource
{{$tableTitle := .table.Title}}
{{$pkType := type "kotlin" .table.PkTypeId}}
/** {{.table.Comment}}服务  */
@Service
class {{.table.Title}}Service {

    @Resource
    lateinit var repo: {{$tableTitle}}Repository

    // 保存{{.table.Comment}}
    fun save{{$tableTitle}}({{.table.Name}}: {{$tableTitle}}Entity): {{$tableTitle}}Entity {
        return this.repo.save({{.table.Name}})
    }

    // 批量保存{{.table.Comment}}
    fun saveAll{{$tableTitle}}(entities:Iterable<{{$tableTitle}}Entity>): Iterable<{{$tableTitle}}Entity>{
        return this.repo.saveAll(entities)
    }

    // 删除{{.table.Comment}}
    fun deleteById(id:{{$pkType}}) {
         this.repo.deleteById(id)
    }

    // 查找{{.table.Comment}}
    fun findById(id: {{$pkType}}):Optional<{{$tableTitle}}Entity> {
        return this.repo.findById(id)
    }
}
