package tto

import (
	"regexp"
	"strings"
	"sync"
)

var (
	predefineRegexp = regexp.MustCompilePOSIX("#\\!([^\\!-]+):([^#]+?)")
	lineJoinRegexp  = regexp.MustCompile("\\s*\\\\(\\s+)")
)

type TemplateKind int
const(
	// 普通模板
	KindNormal = TemplateKind(0)
	// 使用所有表生成模板
	KindTables = TemplateKind(1)
	// 按表前缀生成模板
	KindTablePrefix = TemplateKind(2)
)

type CodeTemplate struct {
	path      string
	template  string
	predefine map[string]string
	kind  TemplateKind
	mux *sync.RWMutex
}

func NewTemplate(s string, path string, attach bool) *CodeTemplate {
	t := &CodeTemplate{path: path,mux: &sync.RWMutex{}}
	return t.resolve(t.attach(s,attach))
}

func (g *CodeTemplate) resolve(s string) *CodeTemplate {
	g.mux.Lock()
	g.predefine = make(map[string]string)
	for _, match := range predefineRegexp.FindAllStringSubmatch(s, -1) {
		g.predefine[match[1]] = match[2]
	}
	g.mux.Unlock()
	g.template = g.format(s)
	// 识别类型
	switch g.predefine["kind"] {
	case "1","tables":
		g.kind = KindTables
	case "2","prefix":
		g.kind = KindTablePrefix
	default:
		g.kind = KindNormal
	}
	return g
}

func (g *CodeTemplate) format(s string) string {
	s = predefineRegexp.ReplaceAllString(s, "")
	s = lineJoinRegexp.ReplaceAllString(s, "")
	return s
}

func (g *CodeTemplate) Kind()TemplateKind{
	return g.kind
}

// 文件路径
func (g *CodeTemplate) FilePath() string {
	return g.path
}

// 获取模板内容
func (g *CodeTemplate) String() string {
	return g.template
}

// 获取预定义的参数
func (g *CodeTemplate) Predefine(key string) (string, bool) {
	g.mux.RLock()
	defer g.mux.RUnlock()
	n, ok := g.predefine[key]
	return n, ok
}



// attach: attach generator copyright at template file first line
func (g *CodeTemplate) attach(s string, attach bool)string {
	if attach {
		ext := g.path[strings.LastIndex(g.path, ".")+1:]
		if ext == "py" {
			return g.python(s)
		}
		if len(s) > 1 && s[0] != '/' {
			if g.isCodeFile(ext) {
				s = `/**
 * this file is auto generated by tto v` + BuildVersion + ` !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 *  please read user guide on https://github.com/ixre/tto
 *
 */
` + s
			}
		}
	}
	return s
}

func (g *CodeTemplate) isCodeFile(ext string) bool {
	return ext == "kt" || ext == "java" || ext == "go" || ext == "ts" || ext == "js" ||
		ext == "cs" || ext == "vb" || ext == "py" || ext == "rb" || ext == "cpp" ||
		ext == "c" || ext == "lua" || ext == "pl"
}
func (g *CodeTemplate) python(s string) string {
	if strings.HasPrefix(s, "#") && !strings.HasPrefix(s, "#!") {
		return s
	}
	return `# 
# this file is auto generated by tto v` + BuildVersion + ` !
# if you want to modify this code,please read guide doc
# and modify code template later.
#
# please read user guide on https://github.com/ixre/tto
#` + s
}
