package tto

import "testing"

func TestTemplate(t *testing.T) {
	tp := NewTemplate(`/**
 * this file is auto generated by tto v{{.global.version}} !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/ixre/tto
 *
 */
!filename:{{.table.Title}}Entity.java
package {{.global.pkg}}.pojo;

 {{range $i,$c := $validateColumns}}\
  column: {{$c.Name}}
 {{end}}

`, "", false)

	t.Log(tp.String())
}

func TestSubstrN(t *testing.T) {
	fn := &internalFunc{}
	s := fn.substrN("admin_user_list", "_", 2)
	println(s)
}

func TestMultiQuota(t *testing.T){
	str := `--, ""
	haha
`
	dg := DBCodeGenerator()
	result := dg.GenerateCode(&Table{Name: "admin_user"}, NewTemplate(str, "", true))
	t.Log("--", result)
}