/**
 * this file is auto generated by TTO-CodeGenerator v{{.version}} !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/ixre/tto
 *
 */
package {{pkg "java" .global.Pkg}}.repo;

import {{pkg "java" .global.Pkg}}.pojo.{{.table.Title}}Entity
import org.springframework.data.jpa.repository.JpaRepository
import org.springframework.data.jpa.repository.Query

/** {{.table.Comment}}仓储接口  */
interface {{.table.Title}}Repository : JpaRepository<{{.table.Title}}Entity, Int> {

}