package go_

var (
	// 实体仓储接口模板
	TPL_ENTITY_REP_INTERFACE = `

            package ifce 

/**
 * this file is auto generated by TTO-CodeGenerator v{{.global.Version}} !
 * if you want to modify this code,please read guide doc
 * and modify code template later.
 *
 * guide please see https://github.com/ixre/tto
 *
 */
!target:{{.global.Pkg}}/ifce/{{.table.Name}}_repo_ifce.go

        import(
            "{{.global.Pkg}}/model"
        )

        type I{{.table.Title}}Repo interface{
            // auto generate by gof
            // Get {{.table.Comment}}
            Get(primary interface{})*model.{{.table.Title}}
            // GetBy {{.table.Comment}}
            GetBy(where string,v ...interface{})*model.{{.table.Title}}
            // Select {{.table.Comment}}
            Select(where string,v ...interface{})[]*model.{{.table.Title}}
            // Save {{.table.Comment}}
            Save(v *model.{{.table.Title}})(int,error)
            // Delete {{.table.Comment}}
            Delete(primary interface{}) error
            // Batch Delete {{.table.Comment}}
            BatchDelete(where string,v ...interface{})(int64,error)
        }`
)
