#!kind:1#!target:vue-pro/views/route.ts
{{$tables := .tables}}

export const autoGeneratedRoutes = [\
{{range $i,$table := .tables}}\
{{$path := name_path $table.Title}}
  {
    path: '{{$path}}/index',
    name: '{{$table.Title}}Index',
    component: () => import(/* webpackChunkName: "{{$table.Name}}-index" */ './{{$path}}/index.vue'),
    meta: {
      // roles: ["admin"],
      title: '{{$table.Comment}}',
      icon: 'list'
    }
  }, \
  {{if not (is_last $i $tables)}},{{end}}
{{end}}\
]
